---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-test
      version: blue
  template:
    metadata:
      name: node-api-test-pod
      labels:
        app: node-api-test
        version: blue
    spec:
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: kubernetes.io/name
      #          operator: In
      #          values:
      #          - n0d3-1
      nodeSelector:
        kubernetes.io/hostname: n0d3-2
      containers:
      - name: node-api-test
        image: josecarlosjr/node_api_test:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "100Mi"
          limits:  
            memory: "200Mi"
            cpu: "200m"
            ephemeral-storage: "500Mi"
        ports:
        - containerPort: 3333
          #hostPort: 3333
        - containerPort: 443
          #hostPort: 443
        
---
apiVersion: v1
kind: Service 
metadata:
  name: node-api-test
  labels:
    app: node-api-test
    service: node-api-test
spec:
  selector:
    app: node-api-test
    version: blue
  type: ClusterIP
  #type: NodePort
  ports:
  - port: 3333
    targetPort: 3333
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: node-api-test

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-api-test-ingress
  namespace: 
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#   nginx.ingress.kubernetes.io/ssl-redirect: "true"
#   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/proxy-redirect-from: http://localhost
    #nginx.ingress.kubernetes.io/proxy-redirect-to: http://localhost:3333
#    nginx.ingress.kubernetes.io/server-snippet: |
#      location = / {       
#        proxy_pass http://localhost:3333/;
#      }
spec:  
#  tls:
#  - hosts:
#      - node-api-test
#    secretName: proxy-ca-secret
#  #type: NodePort
  rules:
  - host: node-api-test
    http:
      paths:
      - path: /
        #pathType: Prefix
        backend:
          serviceName: node-api-test          
          servicePort: 443
          servicePort: 3333
#              #number: 3333
#      - path: /Noticias
#      #  pathType: Prefix
#          serviceName: node-api-test
#          servicePort: 3333
