---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-test
      version: blue
  template:
    metadata:
      name: node-api-test-pod
      labels:
        app: node-api-test
        version: blue
    spec:
      containers:
      - name: node-api-test
        image: josecarlosjr/node_api_test:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service 
metadata:
  name: node-api-test
  labels:
    app: node-api-test
    service: node-api-test
spec:
  selector:
    app: node-api-test
    version: blue
  type: ClusterIP
  #type: NodePort
  ports:
  - port: 80
    targetPort: 3333
    protocol: TCP
  selector:
    app: node-api-test

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-api-test-ingress
  namespace: 
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  #type: NodePort
  rules:
  - host: node-api-test
    http:
      paths:
      - path: /
        #pathType: Prefix
        backend:
          serviceName: node-api-test
          servicePort: 80
              #number: 3333
      #- path: /Noticias
      #  pathType: Prefix
      #    serviceName: node-api-test
      #    servicePort: 3333
